name: 'Run unit tests'
description: 'Installs dependencies and run unit tests'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '18'
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
    - run: npm run test-ci
      shell: bash
