name: 'Code lint'
description: 'Installs dependencies and code lint'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '18'
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
    - run: npm run lint