name: 'Run tests'
description: 'Installs dependencies and runs tests'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '18'
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
    - run: npx playwright install --with-deps
      shell: bash
    - run: npm run e2e
      shell: bash