name: Run Rome lint on PR
on:
  pull_request:
jobs:
  run-commitlint-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint all files
        run: npm run lint
