name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: "Pull request number"
        required: true
      issue_number:
        description: "Issue number"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: PUBLIC_URL="/shri-unit-demo-cra" npm run build
      - name: Deploy 🚀
        id: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
      - name: Update PR and Issue after successful deployment
        if: steps.deploy.outcome == 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const pull_number = ${{ github.event.inputs.pull_request_number }};
            const issue_number = ${{ github.event.inputs.issue_number }};
            const message = 'Deploy was successful.';

            // Close the PR
            await github.rest.pulls.update({ owner, repo, pull_number, state: 'closed' });

            // Add comment to the issue
            await github.rest.issues.createComment({ owner, repo, issue_number, body: message });
