name: Release process
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      issue_number: ${{ steps.create_issue.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install auto-changelog
        run: npm i -g auto-changelog
      - name: Generate changelog
        run: auto-changelog --commit-limit false --template keepachangelog
      - name: Create Issue
        id: create_issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const description = fs.readFileSync('CHANGELOG.md', 'utf8');
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const version = '${{ github.ref }}'.replace('refs/tags/', '');
            const title = `Release ${version} by ${{ github.actor }}`;
            const issue = { owner, repo, labels: ['RELEASE'], body: description, state: "opened" };
            const issues = await github.rest.issues.listForRepo(issue);
            const existingIssue = issues.data.find(i => i.title === title);

            if (existingIssue) {
              await github.rest.issues.update({ ...issue, issue_number: existingIssue.number });
              return existingIssue.number;
            } else {
              const response = await github.rest.issues.create(issue);
              return response.data.number;
            }
  check_issue:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run tests and lint files
        run: |
          npm run test-ci
          npm run e2e
          npm run lint
      - name: Build Project
        run: PUBLIC_URL="/shri-unit-demo-cra" npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
      - name: Close Issue
        if: ${{ success() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = parseInt(${{ needs.release.outputs.issue_number }});
            const [owner, repo] = '${{ github.repository }}'.split('/');
            github.rest.issues.update({
              owner: owner,
              repo: repo,
              issue_number: issueNumber,
              state: "closed"
            });
