name: Release process
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install auto-changelog
        run: npm i -g auto-changelog
      - name: Generate changelog
        run: auto-changelog --output CHANGELOG.md
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const description = fs.readFileSync('CHANGELOG.md', 'utf8');
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const version = '${{ github.ref }}'.replace('refs/tags/', '');
            const issue = { owner, repo, title: `Release ${version} by ${{ github.actor }}`, body: description, label: 'RELEASE' };
            github.rest.issues.create(issue);
  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
  close-issue:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Close Release Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ needs.release.outputs.issue-number }}
          comment: "Deployment was successful. Closing issue."
