name: Release process
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build
  generate-changelog:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Install auto-changelog
        run: npm i -g auto-changelog
      - name: Generate changelog
        run: auto-changelog --output CHANGELOG.md
      - name: Commit and push changelog
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs(fix): Update Changelog by ${GITHUB_ACTOR}"
  release:
    needs: generate-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Release ${GITHUB_REF##*/}
          content-filepath: ./CHANGELOG.md
          labels: RELEASE
  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
  close-issue:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Close Release Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ needs.release.outputs.issue-number }}
          comment: "Deployment was successful. Closing issue."
