name: Release process
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      issue_number: ${{ steps.create_issue.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install auto-changelog
        run: npm i -g auto-changelog
      - name: Generate changelog
        run: auto-changelog --commit-limit false --template keepachangelog
      - name: Create Issue
        id: create_issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const description = fs.readFileSync('CHANGELOG.md', 'utf8');
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const version = '${{ github.ref }}'.replace('refs/tags/', '');
            const title = `Release ${version} by ${{ github.actor }}`;
            const issue = { owner, repo, labels: ['RELEASE'] };
            const issues = await github.rest.issues.listForRepo(issue);
            const existingIssue = issues.data.find(i => i.title === title);

            if (existingIssue) {
              const update = { ...issue, issue_number: existingIssue.number, body: description };
              await github.rest.issues.update(update);
              return existingIssue.number;
            } else {
              const create = { ...issue, title: title, body: description };
              const response = await github.rest.issues.create(create);
              return response.data.number;
            }
  check_issue:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      - name: Run tests and lint files
        id: tests
        run: |
          npm run test-ci || echo "::set-output name=tests_failed::true"
          npm run e2e || echo "::set-output name=tests_failed::true"
          npm run lint || echo "::set-output name=tests_failed::true"
        continue-on-error: true
      - name: Create a comment if test fails
        if: steps.tests.outputs.tests_failed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = parseInt(${{ needs.release.outputs.issue_number }});
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const message = 'The tests or linting failed. Check the logs for more information.';
            github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issueNumber,
              body: message
            });
      - name: Build Project
        if: steps.tests.outputs.tests_failed != 'true'
        run: PUBLIC_URL="/shri-unit-demo-cra" npm run build
      - name: Deploy 🚀
        if: steps.tests.outputs.tests_failed != 'true'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
      - name: Close Issue
        if: ${{ success() }} && steps.tests.outputs.tests_failed != 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = parseInt(${{ needs.release.outputs.issue_number }});
            const [owner, repo] = '${{ github.repository }}'.split('/');
            github.rest.issues.update({
              owner: owner,
              repo: repo,
              issue_number: issueNumber,
              state: "closed"
            });
